apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vw76big4p-nodejs 
  janus-idp.io/tekton: vw76big4p-nodejs
  backstage.io/kubernetes-id: vw76big4p-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vw76big4p-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  